### ISSUE TITLE
Code not working with prertrained models

### ISSUE THREAD

**Issue by euler16** [ShafeenTejani/fast-style-transfer#1]
I am getting "Data loss: Unable to open table file /home/vaio/DevCode/fast-style-transfer/pretrained-networks/starry-night-network/fast_style_network.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
"
What should I do

**Comment by Shoshin23** [comment]
This usually occurs when the checkpoint file isnt' in the same folder as your other model files or the files are corrupted. Try re-downloading again. :)
